language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_script:
  - echo 'America/Chicago' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - sudo ntpdate ntp.ubuntu.com

script: bundle exec rake spec

services:
  - mongodb
