defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: cbs_development

test:
  <<: *defaults
  database: cbs_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: 198.199.90.247
  port: 27017
  database: cbs
  # slaves:
  #   - host: 10.178.129.158
  #   - host: 10.178.129.153
  #   - host: 10.178.128.160